contents= open("new.txt","w")
contents.write(input("Enter the content you want to write:"))
print("data successfully written")
contents.close()
contents=open("new.txt","a")
contents.write(input("Enter additional text to append:"))
print("data successfully written")
contents.close()
contents=open("new.txt","r")
print("The final content of output.txt file:")
print(contents.read())
contents.close()
